// ALTERNATIVE NOT TAKEN (2026-09-22) — see evm/README.md.
// ZVAULT v1 ships on Zcash (transparent OP_RETURN + indexer), not EVM.
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @notice Poseidon(2) hasher, deployed separately (generated by circomlibjs).
interface IPoseidon2 {
    function poseidon(uint256[2] calldata input) external pure returns (uint256);
}

/// @notice Groth16 verifier for the reveal circuit, generated by snarkjs.
interface IRevealVerifier {
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[5] calldata publicSignals
    ) external view returns (bool);
}

interface IBurnToken {
    function burnFrom(address from, uint256 amount) external;
}

/**
 * HASHVAULT
 *
 * A proof-of-work mint whose output is sealed.
 *
 * Mining is public and Keccak-based: you grind a nonce until
 * keccak256(challenge, miner, nonce) falls below a target. That is cheap to
 * verify on chain and needs no proof system.
 *
 * What you receive is not a token but a leaf in a Merkle tree — a Poseidon
 * commitment binding four inputs you chose and a seed you alone can open.
 * Nobody, including you, learns the traits until you reveal. Reveal is a
 * Groth16 proof that the score was computed correctly from the bound inputs.
 *
 * Leaves accumulate into epochs. A reveal proves membership in an epoch's tree
 * without saying which leaf, so the anonymity set is the epoch's mint count.
 * This is the only reason epochs exist — do not shrink them for UX.
 *
 * THE FOUR INPUTS, and why money is the weakest:
 *   work     0.40  difficulty bits above base. Costs compute, not capital.
 *   patience 0.25  epochs sealed before reveal is permitted. Unbuyable.
 *   burn     0.25  tokens destroyed at mint. The sink.
 *   money    0.10  premium paid over the floor mint price. Capped, minor.
 *
 * Each contributes sqrt(x / x_max) * weight, so the first unit of any input
 * matters far more than the thousandth. Ten times the spend buys roughly three
 * times the edge. Whales are advantaged, never decisive.
 *
 * Weights and caps are public and immutable. The formula is meant to be read,
 * modelled and argued about. Only the state is hidden.
 */
contract HashVault {
    // ---------------------------------------------------------------- config

    uint256 public constant SUPPLY_CAP = 4096;
    uint256 public constant TREE_DEPTH = 20;

    // Scoring weights, basis points, must sum to 10_000.
    uint256 public constant W_WORK = 4000;
    uint256 public constant W_PATIENCE = 2500;
    uint256 public constant W_BURN = 2500;
    uint256 public constant W_MONEY = 1000;

    // Input ceilings. Past these, additional spend buys nothing at all.
    uint256 public constant MAX_WORK_BITS = 12;      // above base difficulty
    uint256 public constant MAX_PATIENCE = 16;       // epochs sealed
    uint256 public constant MAX_BURN = 5000 ether;   // burn token units
    uint256 public constant MAX_MONEY = 4;           // multiples of floor price

    uint256 public constant BASE_DIFFICULTY_BITS = 26;
    uint256 public constant EPOCH_SIZE = 128;        // leaves per anonymity set

    IPoseidon2 public immutable poseidon;
    IRevealVerifier public immutable revealVerifier;
    IBurnToken public immutable burnToken;
    address public immutable treasury;

    // ----------------------------------------------------------------- state

    uint256 public minted;
    uint256 public currentEpoch;
    uint256 public leavesInEpoch;

    /// Finalised Merkle root per epoch. Reveals prove against these.
    mapping(uint256 => uint256) public epochRoot;

    /// Incremental tree state for the epoch being filled.
    uint256[TREE_DEPTH] internal filledSubtrees;
    uint256[TREE_DEPTH] internal zeros;
    uint256 internal nextIndex;

    /// Spent reveal nullifiers. One reveal per commitment, ever.
    mapping(uint256 => bool) public revealed;

    /// Ownership nullifiers for private transfer.
    mapping(uint256 => bool) public spent;

    /// The challenge every miner grinds against. Rotates on each mint so no
    /// solution can be banked, and no farm can pre-compute the collection.
    bytes32 public challenge;

    event Mined(
        uint256 indexed epoch,
        uint256 leafIndex,
        uint256 commitment,
        uint256 workBits,
        uint256 patience,
        uint256 burnAmount,
        uint256 moneyMultiple
    );
    event EpochSealed(uint256 indexed epoch, uint256 root, uint256 leaves);
    event Revealed(uint256 indexed epoch, uint256 nullifier, uint256 score, uint256 traitHash);
    event Transferred(uint256 nullifier, uint256 newCommitment);

    error BadProofOfWork();
    error SupplyExhausted();
    error InputOutOfRange();
    error Underpaid();
    error AlreadyRevealed();
    error AlreadySpent();
    error UnknownRoot();
    error PatienceNotServed();
    error InvalidProof();

    constructor(
        address _poseidon,
        address _revealVerifier,
        address _burnToken,
        address _treasury
    ) {
        poseidon = IPoseidon2(_poseidon);
        revealVerifier = IRevealVerifier(_revealVerifier);
        burnToken = IBurnToken(_burnToken);
        treasury = _treasury;
        challenge = keccak256(abi.encodePacked(block.chainid, address(this), blockhash(block.number - 1)));
        _initZeros();
    }

    // ------------------------------------------------------------ mint price

    /**
     * Floor price follows a staircase rather than a smooth curve. A staircase
     * is legible — a miner can see the next step coming and decide whether to
     * race it. Hashcats derives price as supply * step, which climbs forever
     * and eventually prices out its own miners; that is visible in its stall.
     * The top step here is deliberately reachable.
     */
    function floorPrice() public view returns (uint256) {
        uint256 n = minted;
        if (n < 256) return 0.25 ether / 100;   // 0.0025
        if (n < 512) return 0.01 ether;
        if (n < 1024) return 0.03 ether;
        if (n < 2048) return 0.08 ether;
        return 0.15 ether;
    }

    /// Difficulty rises with supply, and separately with the miner's own bid.
    function baseDifficulty() public view returns (uint256) {
        uint256 n = minted;
        if (n < 256) return BASE_DIFFICULTY_BITS;
        if (n < 1024) return BASE_DIFFICULTY_BITS + 2;
        if (n < 2048) return BASE_DIFFICULTY_BITS + 4;
        return BASE_DIFFICULTY_BITS + 6;
    }

    // ------------------------------------------------------------------ mine

    /**
     * Submit a proof of work together with a sealed commitment.
     *
     * `commitment` must equal
     *     Poseidon(Poseidon(secret, seed), Poseidon(inputHash, salt))
     * where inputHash = Poseidon(Poseidon(workBits, patience), Poseidon(burn, money)).
     *
     * The contract cannot check that — it never sees the secret. It instead
     * records the inputs it observed in the event log and, at reveal time, the
     * circuit proves the opened inputs hash to a leaf that exists in the tree.
     * A miner who commits to inputs richer than the ones actually paid for
     * produces a leaf that is in the tree but whose opening the circuit will
     * reject, so the lie costs them the mint and gains nothing.
     */
    function mine(
        uint256 nonce,
        uint256 commitment,
        uint256 workBits,
        uint256 patience,
        uint256 burnAmount,
        uint256 moneyMultiple
    ) external payable {
        if (minted >= SUPPLY_CAP) revert SupplyExhausted();
        if (
            workBits > MAX_WORK_BITS ||
            patience > MAX_PATIENCE ||
            burnAmount > MAX_BURN ||
            moneyMultiple > MAX_MONEY
        ) revert InputOutOfRange();

        // Work is bid: the miner chooses to grind harder for a better roll.
        uint256 bits = baseDifficulty() + workBits;
        bytes32 h = keccak256(abi.encodePacked(challenge, msg.sender, nonce));
        if (uint256(h) >= (type(uint256).max >> bits)) revert BadProofOfWork();

        uint256 price = floorPrice() * (1 + moneyMultiple);
        if (msg.value < price) revert Underpaid();

        if (burnAmount > 0) burnToken.burnFrom(msg.sender, burnAmount);

        uint256 index = _insert(commitment);
        minted += 1;
        leavesInEpoch += 1;

        // Rotate the challenge. Binding to the new supply and this mint's hash
        // means the next puzzle cannot exist until this one is settled.
        challenge = keccak256(abi.encodePacked(h, minted, block.timestamp));

        emit Mined(currentEpoch, index, commitment, workBits, patience, burnAmount, moneyMultiple);

        if (leavesInEpoch == EPOCH_SIZE) _sealEpoch();

        (bool ok, ) = treasury.call{value: address(this).balance}("");
        require(ok, "payout failed");
    }

    function _sealEpoch() internal {
        uint256 root = filledSubtrees[TREE_DEPTH - 1];
        epochRoot[currentEpoch] = root;
        emit EpochSealed(currentEpoch, root, leavesInEpoch);
        currentEpoch += 1;
        leavesInEpoch = 0;
        nextIndex = 0;
        _initZeros();
    }

    /// Anyone may seal a stale epoch so that holders are never stranded
    /// waiting for an anonymity set that will not fill.
    function forceSealEpoch() external {
        require(leavesInEpoch > 0, "empty");
        require(minted >= SUPPLY_CAP || block.timestamp > _epochDeadline(), "too early");
        _sealEpoch();
    }

    uint256 public epochStartedAt = block.timestamp;
    function _epochDeadline() internal view returns (uint256) {
        return epochStartedAt + 7 days;
    }

    // ---------------------------------------------------------------- reveal

    /**
     * Open a commitment. The proof establishes, without naming the leaf:
     *   1. knowledge of a leaf in `epochRoot[epoch]` and its opening
     *   2. that `score` is the correct weighted sqrt combination of the
     *      inputs bound inside that leaf
     *   3. that `traitHash` derives from the committed seed and secret
     *   4. that `nullifier` is derived from the secret, so this leaf opens once
     *
     * Public signals: [root, nullifier, score, traitHash, patienceServed]
     */
    function reveal(
        uint256 epoch,
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[5] calldata pub
    ) external {
        uint256 root = epochRoot[epoch];
        if (root == 0 || pub[0] != root) revert UnknownRoot();
        if (revealed[pub[1]]) revert AlreadyRevealed();

        // Patience is enforced here rather than in the circuit: the circuit
        // proves the committed patience value, the chain proves time passed.
        if (currentEpoch < epoch + pub[4]) revert PatienceNotServed();

        if (!revealVerifier.verifyProof(a, b, c, pub)) revert InvalidProof();

        revealed[pub[1]] = true;
        emit Revealed(epoch, pub[1], pub[2], pub[3]);
    }

    // -------------------------------------------------------------- transfer

    /**
     * Private transfer. Spend a nullifier, insert a fresh commitment. The link
     * between old and new owner is broken; observers learn only that some leaf
     * moved. Reuses the reveal verifier's membership machinery via a separate
     * circuit in production — kept minimal here.
     */
    function transfer(uint256 nullifier, uint256 newCommitment) external {
        if (spent[nullifier]) revert AlreadySpent();
        spent[nullifier] = true;
        _insert(newCommitment);
        emit Transferred(nullifier, newCommitment);
    }

    // ------------------------------------------------------------ merkle impl

    function _insert(uint256 leaf) internal returns (uint256) {
        uint256 index = nextIndex;
        uint256 current = leaf;
        uint256 path = index;

        for (uint256 i = 0; i < TREE_DEPTH; i++) {
            if (path % 2 == 0) {
                filledSubtrees[i] = current;
                current = poseidon.poseidon([current, zeros[i]]);
            } else {
                current = poseidon.poseidon([filledSubtrees[i], current]);
                filledSubtrees[i] = current;
            }
            path /= 2;
        }
        filledSubtrees[TREE_DEPTH - 1] = current;
        nextIndex = index + 1;
        return index;
    }

    function _initZeros() internal {
        uint256 z = uint256(keccak256("hashvault.empty.leaf")) >> 8;
        for (uint256 i = 0; i < TREE_DEPTH; i++) {
            zeros[i] = z;
            z = poseidon.poseidon([z, z]);
        }
    }

    // ------------------------------------------------------------- read-only

    /**
     * Off-chain mirror of the circuit's scoring, so a front end can show a
     * miner what a given bid would be worth before they spend on it. Integer
     * sqrt at 1e6 precision; the circuit reproduces this exactly.
     */
    function previewScore(
        uint256 workBits,
        uint256 patience,
        uint256 burnAmount,
        uint256 moneyMultiple
    ) external pure returns (uint256) {
        uint256 s;
        s += W_WORK * _sqrtRatio(workBits, MAX_WORK_BITS);
        s += W_PATIENCE * _sqrtRatio(patience, MAX_PATIENCE);
        s += W_BURN * _sqrtRatio(burnAmount, MAX_BURN);
        s += W_MONEY * _sqrtRatio(moneyMultiple, MAX_MONEY);
        return s / 10_000; // 0 .. 1e6
    }

    function _sqrtRatio(uint256 x, uint256 max) internal pure returns (uint256) {
        if (x == 0) return 0;
        if (x >= max) return 1e6;
        return _sqrt((x * 1e12) / max);
    }

    function _sqrt(uint256 x) internal pure returns (uint256 y) {
        uint256 z = (x + 1) / 2;
        y = x;
        while (z < y) {
            y = z;
            z = (x / z + z) / 2;
        }
    }
}
